package com.qt.sales.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.qt.sales.model.Announcement;
import com.qt.sales.model.AnnouncementExample;

public interface AnnouncementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_FANS_SYS_NOTICE
     *
     * @mbggenerated Tue Nov 08 12:24:25 CST 2016
     */
    int countByExample(AnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_FANS_SYS_NOTICE
     *
     * @mbggenerated Tue Nov 08 12:24:25 CST 2016
     */
    int deleteByExample(AnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_FANS_SYS_NOTICE
     *
     * @mbggenerated Tue Nov 08 12:24:25 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_FANS_SYS_NOTICE
     *
     * @mbggenerated Tue Nov 08 12:24:25 CST 2016
     */
    int insert(Announcement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_FANS_SYS_NOTICE
     *
     * @mbggenerated Tue Nov 08 12:24:25 CST 2016
     */
    int insertSelective(Announcement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_FANS_SYS_NOTICE
     *
     * @mbggenerated Tue Nov 08 12:24:25 CST 2016
     */
    List<Announcement> selectByExample(AnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_FANS_SYS_NOTICE
     *
     * @mbggenerated Tue Nov 08 12:24:25 CST 2016
     */
    Announcement selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_FANS_SYS_NOTICE
     *
     * @mbggenerated Tue Nov 08 12:24:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") Announcement record, @Param("example") AnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_FANS_SYS_NOTICE
     *
     * @mbggenerated Tue Nov 08 12:24:25 CST 2016
     */
    int updateByExample(@Param("record") Announcement record, @Param("example") AnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_FANS_SYS_NOTICE
     *
     * @mbggenerated Tue Nov 08 12:24:25 CST 2016
     */
    int updateByPrimaryKeySelective(Announcement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_FANS_SYS_NOTICE
     *
     * @mbggenerated Tue Nov 08 12:24:25 CST 2016
     */
    int updateByPrimaryKey(Announcement record);
}